version: "3.0"
services:
    db:
      container_name: "db"
      image: postgres:14.1-alpine
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
          - POSTGRES_PORT=5432
          - POSTGRES_HOST=db
          - POSTGRES_HOST_AUTH_METHOD=trust
          - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
          - "5432:5432"
      networks:
          - custom
    pgadmin:
      container_name: "pgadmin"
      image: dpage/pgadmin4
      restart: always
      environment:
          - PGADMIN_DEFAULT_EMAIL=HnH2v@example.com
          - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
          - "5050:80"
      networks:
          - custom

networks:
    custom:
      driver: bridge